version: "3"

services:
    rabbitmq-container:
        image: rabbitmq:3-management
        ports:
            - "4369:4369"
            - "5672:5672"
            - "15672:15672"
            - "55950:55950"
        volumes:
            - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
            - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    sender:
        image: "sender"
        hostname: "sender"
        build:
            context: messagesender/
            dockerfile: ./src/main/resources/docker/Dockerfile
        ports:
            - 8080:8080
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq-container
        depends_on:
            - rabbitmq-container
    receiver:
        image: "receiver"
        hostname: "receiver"
        build:
            context: messagereceiver/
            dockerfile: ./src/main/resources/docker/Dockerfile
        ports:
          - 8082:8082
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq-container
        depends_on:
          - rabbitmq-container
          - sender
